version: '3'

services:
    commerce_db:
        image: postgres
        env_file: .env
        environment:
            POSTGRES_DB: ${TYPEORM_DATABASE}
            POSTGRES_USER: ${TYPEORM_USERNAME}
            POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
        ports:
            - "5432:5432"
        networks:
            mec_network:
                ipv4_address: 172.28.0.2
    commerce_sys:
        env_file: .env
        build: .
        command: npm run start:debug
        volumes:
            - .:/code
        ports:
            - "${API_PORT}:${API_PORT}"
            - "9229:9229"
        networks:
            - mec_network

networks:
    mec_network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.28.0.0/16"
