version: '3'

services:
    commerce_sys:
        env_file: .env
        build: .
        command: npm run start:debug
        volumes:
            - .:/code
        ports:
            - "${API_PORT}:${API_PORT}"
            - "9232:9232"
networks:
    default:
        name: api
        external: true
